### ISSUE TITLE
Return redirect

### ISSUE THREAD

**Issue by ire4ever1190** [ire4ever1190/mike-old#7]
Just something simple for hacktoberfest

**Comment by grvsood** [comment]
Can you provide more details about the issue?

**Comment by ire4ever1190** [comment]
In the response to a request, there should be a proc that returns a redirect so that the user is redirected to a different url

**Comment by other019** [comment]
So basically, you want a snippet like 
```nim
import mike

get "/re":
    redirect "/hello"

get "/hello":
	send("Hello, world!")

startServer()
```
It will bounce the user from `/re` endpoint to `/hello/ with  301 or 308 http response code by default. User could also choose the response code from range 3xx? Am I right?

**Comment by ire4ever1190** [comment]
yup, that's correct
